spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunboat?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,WEB-INFO/**
