spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunboat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,WEB-INFO/**
